eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8769/eureka/,http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi
    
version = version 1